# Generated by Django 3.1.4 on 2020-12-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201224_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
