# Generated by Django 3.1.4 on 2020-12-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201226_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
